### ISSUE TITLE
list index out of range error while running main.py

### ISSUE THREAD

**Issue by sushmas88** [DongjunLee/hb-config#1]
Hi DongjunLee,
                    My stack is python3.6
                                       tensorflow1.4
                                      hb-config0.3.3 
                                      pycharm IDE 2017
                     I am impressed by working with your code.I'm currently  working with RNN.I have gone through your code which is written using High level API'S like Estimators,Dataset and Experiment,But i'm facing error while running main.py file as follows....

Traceback (most recent call last):
  File "/home/PycharmProjects/conversation-tensorflow-master/main.py", line 38, in <module>
    Config(args.config)
  File "/home/virtual-3.6/lib/python3.6/site-packages/hbconfig/__init__.py", line 23, in __call__
    self.config = self.read_file(fname)
  File "/home/virtual-3.6/lib/python3.6/site-packages/hbconfig/__init__.py", line 32, in read_file
    config_file = config_files[0]
IndexError: list index out of range

Kindly resolve this issue at the earliest..
Thanks in advance.

**Comment by DongjunLee** [comment]
Hi @sushmas88 
Thank you for issuing!

First of all, maybe the error was due to typo when you entered the config name.
If you enter the config name correctly, there will be no problem. :)

I'll fix it right now

**Comment by DongjunLee** [comment]
I fixed this issue and deploy to pip.
you can upgrade hb-config with this command.

```pip install --upgrade hb-config```

**Comment by sushmas88** [comment]
My issue in not resolved by doing above changes. Below is the link right now i'm working on-
[here](https://github.com/DongjunLee/conversation-tensorflow)

Now, i'm getting following error in main.py file as follows...
 
  File "main.py", line 38, in <module>
    Config(args.config)
  File "/home/virtual-3.6/lib/python3.6/site-packages/hbconfig/__init__.py", line 25, in __call__
    self.config = self.read_file(fname)
  File "/home/virtual-3.6/lib/python3.6/site-packages/hbconfig/__init__.py", line 32, in read_file
    raise FileNotFoundError(f"No such files start filename '{fname}'")
FileNotFoundError: No such files start filename '/home/PycharmProjects/conversation-tensorflow-master/config/check_tiny.yml'
  
Please resolve this...

**Comment by DongjunLee** [comment]
Hmm.. 

@sushmas88 could you check the config file exist?
file path is '/home/sushma/PycharmProjects/conversation-tensorflow-master/config/check_tiny.yml'

**Comment by sushmas88** [comment]
yes. config file is exactly in  that path only.

**Comment by DongjunLee** [comment]
Did you enter this command?  
```python main.py --config check_tiny --mode train```

if you entered this command and config file that start file name as 'check_tiny' didn't not exist,
hb-config raise error message like this ```FileNotFoundError: No such files start filename check_tiny' ```

can you check it again?

**Comment by sushmas88** [comment]
@DongjunLee 
/PycharmProjects/conversation-tensorflow-master$ python3.6 main.py --config /home/sushma/PycharmProjects/conversation-tensorflow-master/config/check_tiny.yml --mode train

i'm giving this command in pycharm terminal but the error remains same.
i have kept that check_tiny.yml in my pycharm directory.
please do resolve this..

**Comment by DongjunLee** [comment]
I understand the problem. :)

just enter this command.
```python3.6 main.py --config check_tiny --mode train```

not
```python3.6 main.py --config /home/sushma/PycharmProjects/conversation-tensorflow-master/config/check_tiny.yml --mode train```

I will fix it can enter the full path of config.

**Comment by sushmas88** [comment]
@DongjunLee 
Thanks Now its working...

**Comment by DongjunLee** [comment]
Thanks :)
