### ISSUE TITLE
Not work with python3.5?

### ISSUE THREAD

**Issue by allanj** [DongjunLee/hb-config#4]
It happens to be the error below. 

`allan@statnlp0:~/projects/partialner_pytorch$` python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hbconfig import Config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/hbconfig/__init__.py", line 40
    raise FileNotFoundError(f"No such files start filename '{fname}'")
                                                                    ^
SyntaxError: invalid syntax
`

**Comment by DongjunLee** [comment]
yeah, this package requires python 3.6 +.
